# fly.toml app configuration file generated for lubieniebieski-api on 2023-11-18T21:02:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lubieniebieski-api"
primary_region = "waw"


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[mounts]]
source = "links_data_machines"
destination = "/data"
processes = ["app"]
